In [1]:
#Load in the food inspection data provided by the city of Chicago

In [4]:
import numpy as np
import pandas as pd
import csv

In [5]:
food_inspect = pd.read_csv("Food_Inspections.csv")

In [6]:
#what's the size of the df? 
len(food_inspect)

216593

In [8]:
food_inspect.head()

,Inspection ID,DBA Name,AKA Name,License #,Facility Type,Risk,Address,City,State,Zip,Inspection Date,Inspection Type,Results,Violations,Latitude,Longitude,Location
0,2484856,VOLARE,VOLARE,2141813.0,Restaurant,Risk 1 (High),201 E GRAND AVE,CHICAGO,IL,60611.0,02/17/2021,Canvass,Out of Business,NaN,41.891652,-87.622604,"(-87.62260381408842, 41.89165221441017)"
1,2473041,ROSATI'S GRANT PARK,ROSATI'S,2762683.0,Restaurant,Risk 1 (High),23 E ADAMS ST,CHICAGO,IL,60603.0,01/22/2021,License,Pass,NaN,41.879391,-87.626848,"(-87.62684825563626, 41.879391313239694)"
2,2456537,ACE BOUNCE,ACE BOUNCE,2431682.0,Restaurant,Risk 1 (High),230 N CLARK ST,CHICAGO,IL,60601.0,11/12/2020,Non-Inspection,No Entry,NaN,41.886552,-87.631142,"(-87.63114162542584, 41.88655161219518)"
3,2454019,TACO MAYA,TACO MAYA,2757393.0,Catering,Risk 1 (High),5055 W DIVERSEY AVE,CHICAGO,IL,60639.0,10/29/2020,License,Not Ready,NaN,41.931328,-87.753683,"(-87.75368264650402, 41.93132774430297)"
4,2453550,BIAN,BIAN,2744751.0,Restaurant,Risk 1 (High),600 W CHICAGO AVE,CHICAGO,IL,60654.0,10/20/2020,License,Pass,NaN,41.896585,-87.642996,"(-87.64299618172501, 41.896585191199556)"

In [24]:
#convert inspection date to datetime object 
#year-month-day
food_inspect['Inspection Date'] = pd.to_datetime(food_inspect['Inspection Date'])
food_inspect.head()

,Inspection ID,DBA Name,AKA Name,License #,Facility Type,Risk,Address,City,State,Zip,Inspection Date,Inspection Type,Results,Violations,Latitude,Longitude,Location
0,2484856,VOLARE,VOLARE,2141813.0,Restaurant,Risk 1 (High),201 E GRAND AVE,CHICAGO,IL,60611.0,2021-02-17,Canvass,Out of Business,NaN,41.891652,-87.622604,"(-87.62260381408842, 41.89165221441017)"
1,2473041,ROSATI'S GRANT PARK,ROSATI'S,2762683.0,Restaurant,Risk 1 (High),23 E ADAMS ST,CHICAGO,IL,60603.0,2021-01-22,License,Pass,NaN,41.879391,-87.626848,"(-87.62684825563626, 41.879391313239694)"
2,2456537,ACE BOUNCE,ACE BOUNCE,2431682.0,Restaurant,Risk 1 (High),230 N CLARK ST,CHICAGO,IL,60601.0,2020-11-12,Non-Inspection,No Entry,NaN,41.886552,-87.631142,"(-87.63114162542584, 41.88655161219518)"
3,2454019,TACO MAYA,TACO MAYA,2757393.0,Catering,Risk 1 (High),5055 W DIVERSEY AVE,CHICAGO,IL,60639.0,2020-10-29,License,Not Ready,NaN,41.931328,-87.753683,"(-87.75368264650402, 41.93132774430297)"
4,2453550,BIAN,BIAN,2744751.0,Restaurant,Risk 1 (High),600 W CHICAGO AVE,CHICAGO,IL,60654.0,2020-10-20,License,Pass,NaN,41.896585,-87.642996,"(-87.64299618172501, 41.896585191199556)"

In [29]:
#all inspections since Jan 1, 2019
inspect_subset = food_inspect[food_inspect['Inspection Date'] > '2019-01-01']

In [31]:
#cut down so from jan 1, 2019 - march 1, 2020 
inspect_subset = inspect_subset[inspect_subset["Inspection Date"] < "2020-03-01"]
len(inspect_subset)

22104

In [35]:
#sort it by date
inspect_subset = inspect_subset.sort_values(by = ["Inspection Date"])

In [36]:
inspect_subset.head()

,Inspection ID,DBA Name,AKA Name,License #,Facility Type,Risk,Address,City,State,Zip,Inspection Date,Inspection Type,Results,Violations,Latitude,Longitude,Location
37611,2243958,FAMILY DOLLART #32124,FAMILY DOLLAR,2630979.0,Grocery Store,Risk 3 (Low),1633 W MONTEREY AVE,CHICAGO,IL,60643.0,2019-01-02,License,Not Ready,NaN,41.689432,-87.663014,"(-87.66301447393185, 41.689431926833365)"
38793,2243957,TWO MILE COFFEE BAR,TWO MILE COFEE BAR,2641611.0,Restaurant,Risk 2 (Medium),1766 W 95TH ST,CHICAGO,IL,60643.0,2019-01-02,License,Not Ready,NaN,41.721260,-87.667257,"(-87.66725709711507, 41.72126016238349)"
39041,2243961,MR. POLLO,MR. POLLO,2542966.0,Restaurant,Risk 1 (High),3026 W BELMONT AVE,CHICAGO,IL,60618.0,2019-01-02,Canvass,Pass w/ Conditions,"3. MANAGEMENT, FOOD EMPLOYEE AND CONDITIONAL E...",41.939467,-87.703811,"(-87.70381061827938, 41.93946745056518)"
39502,2243966,EL CENTENARIO SPORTS BAR & GRILL,EL CENTENARIO SPORTS BAR & GRILL,2270539.0,Restaurant,Risk 1 (High),4556 W ROOSEVELT RD,CHICAGO,IL,60624.0,2019-01-02,Canvass,Out of Business,NaN,41.866072,-87.739770,"(-87.73976972613504, 41.866071937099434)"
37922,2243960,AVONDALE TAP,AVONDALE TAP,2368771.0,Restaurant,Risk 1 (High),3634 W BELMONT AVE,CHICAGO,IL,60618.0,2019-01-02,Canvass,No Entry,NaN,41.939308,-87.718735,"(-87.71873540202452, 41.939307518988336)"

In [37]:
inspect_subset.tail()

,Inspection ID,DBA Name,AKA Name,License #,Facility Type,Risk,Address,City,State,Zip,Inspection Date,Inspection Type,Results,Violations,Latitude,Longitude,Location
18116,2363066,TAQUERIA LA MORENA,TAQUERIA LA MORENA,2717978.0,Restaurant,Risk 1 (High),4530 W AUGUSTA BLVD,CHICAGO,IL,60651.0,2020-02-28,License,Pass w/ Conditions,"3. MANAGEMENT, FOOD EMPLOYEE AND CONDITIONAL E...",41.898910,-87.739737,"(-87.73973687557414, 41.89890960102938)"
17346,2363087,ARTURO'S TACOS,ARTURO'S TACOS,17234.0,Restaurant,Risk 1 (High),2001 N WESTERN AVE,CHICAGO,IL,60647.0,2020-02-28,Canvass Re-Inspection,Pass,39. CONTAMINATION PREVENTED DURING FOOD PREPAR...,41.917608,-87.687264,"(-87.68726399716304, 41.91760789157746)"
19262,2363060,TBD,SHERIDAN 'L' LIQUORS AND LOUNGE,2712488.0,Liquor,Risk 3 (Low),3944-3946 N SHERIDAN RD,CHICAGO,IL,60613.0,2020-02-28,License,Pass,NaN,41.954060,-87.654680,"(-87.65468014494112, 41.95405970426544)"
15583,2363140,FARNSWORTH SCHOOL,FARNSWORTH SCHOOL,23161.0,School,Risk 1 (High),5414 N Linder (5500W),CHICAGO,IL,60630.0,2020-02-28,Canvass Re-Inspection,Pass,NaN,41.979809,-87.766108,"(-87.76610809089279, 41.97980919943396)"
18297,2363086,TASTY FAST FOOD & GROCERY,TASTY FAST FOOD & GROCERY,2559536.0,Restaurant,Risk 1 (High),6645 S HALSTED ST,CHICAGO,IL,60621.0,2020-02-28,Complaint Re-Inspection,Pass,NaN,41.772966,-87.644463,"(-87.6444630706756, 41.77296602950113)"

In [38]:
inspect_subset.to_csv("inspect_rests.csv")
#still too big to upload to github. Maybe cutting down the columns will help?

In [39]:
rest_subset = inspect_subset.drop(columns = ["Inspection ID", "License #", "Risk", "City", "State"])

In [41]:
rest_subset.to_csv("rest_subset.csv")